[package]
name = "MorphoAptos"
version = "1.0.0"
authors = []

[addresses]
account = "0x260fb5bbfcd34dc762b2ff0cb70e76dd1572eea6de286d9c7bc750ed71d48492"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
